### ISSUE TITLE
#bug# 重复的Alignments值

### ISSUE THREAD

**Issue by ghost** [CNGB-DC/Biomigo#3]
![qq 20161017175044](https://cloud.githubusercontent.com/assets/12521320/19433239/634a877a-9492-11e6-8feb-04f5ab6b6f01.png)

Alignments的值出现了两个20000，建议修改一下！@adam-chuan

**Comment by adam-chuan** [comment]
嗯，好的，明天回办公室修改！-------- 原始邮件 --------主题：[CNGB-DC/Biomigo] 重复的Alignments值 (#3)发件人：Steven Shen 收件人：CNGB-DC/Biomigo 抄送：Adam ,Mention 

Alignments的值出现了两个20000，建议修改一下！@adam-chuan 

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CNGB-DC/Biomigo","title":"CNGB-DC/Biomigo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CNGB-DC/Biomigo"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"重复的Alignments值 (#3)"}],"action":{"name":"View Issue","url":"https://github.com/CNGB-DC/Biomigo/issues/3"}}}

**Comment by adam-chuan** [comment]
内网已经将其中一个20000改为2000，下一步让felix统一更新到外网，请知悉！

**Comment by nixiaoya** [comment]
Modify confirmed, Close issue
